default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Twitter-clone_development

test:
  <<: *default
  database: Twitter-clone_test

production:
  <<: *default
  database: Twitter-clone_production
  username: Twitter-clone
  password: <%= ENV['TWITTER-CLONE_DATABASE_PASSWORD'] %>
